import BlogPostBanner from "@/components/BlogPostBanner/BlogPostBanner";
import BlogPostCard from "@/components/BlogPostCard/BlogPostCard";
import Head from "next/head";


const Index = () => {

    return (
      <>
          <Head>
              <title>Exchange-Blog</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className={"p-6 gap-10 lg:px-8"}>
              <BlogPostBanner/>
              <div className="grid gap-10 lg:grid-cols-3 grid-cols-1">
                  <BlogPostCard/>
                  <BlogPostCard/>
                  <BlogPostCard/>
                  <BlogPostCard/>
                  <BlogPostCard/>
                  <BlogPostCard/>
                  <BlogPostCard/>
                  <BlogPostCard/>
                  <BlogPostCard/>
                  <BlogPostCard/>
                  <BlogPostCard/>
                  <BlogPostCard/>
              </div>
          </div>
      </>

    )
}


export default Index;