import Head from "next/head";
import Style from "@/styles/components/MainBlock.module.scss";
import Image from "next/image";
import IndexPic from "@/assets/images/IndexPic.png";
import Auth from "@/styles/components/Auth.module.scss";
import Link from "next/link";
import ArrowLeft from "@/assets/svg/arrow-left.svg";
import OtpInput from 'react-otp-input';
import OtherLogin from "@/assets/images/otherLogin.png";
import useTitle from "@/CustomHook/useTitle";
import {useState} from "react";
import EditMail from "@/assets/svg/editMail.svg"
import Counter from "@/components/Counter/Counter";

const Otp = () => {
    useTitle("otp")

    const [otp, setOtp] = useState('');

    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className={"p-6 gap-10 text-white lg:px-8"}>
                <div className={`flex items-center ${Style.mainBlock}`}>
                    <Image className={Style.indexPic} src={IndexPic} alt={"exchanger-web"}/>
                    <h1 className={`text-center ${Style.indexTitle}`}>
            <span className={`${Style.boldTitle} font-bold`}>
              <span className={Style.greenTitle}>A</span>RZICLUB
            </span>
                        <span className={Style.lightTitle}>
               EXCHANGER
            </span>
                    </h1>

                    <div className={`relative w-1/2 flex flex-col items-start ${Auth.loginBox}`}>

                        <div className={"flex w-full items-center justify-between"}>

                            <Link href={"/auth"}
                                  className={`flex relative items-center justify-center ${Auth.backBtn}`}>
                                <Image src={ArrowLeft} alt={"back"} className={"absolute left-[8px]"}/>

                                <p className={"font-bold text-center ml-[8px]"}>
                                    Back
                                </p>
                            </Link>

                            <div className={"flex items-center"}>
                                <p className={"lg:text-[18px] text-[12px] font-bold"}>
                                    Enter the password
                                </p>
                            </div>
                        </div>

                        <p className={"text-[13px] mb-[20px] mt-[10px]"}>
                            To use ARZICLUB services , log in to your account . <Link href={"/auth"}
                                                                                      className={`font-bold ${Auth.registerLink}`}>Login</Link> if
                            you don't have an account .
                        </p>

                        <div className={"flex  w-full relative items-center justify-between"}>

                            <OtpInput
                                value={otp}
                                onChange={setOtp}
                                numInputs={6}
                                renderSeparator={<span></span>}
                                inputStyle={{
                                    background: "var(--area-bg)",
                                    marginRight: 10,
                                    width: 40, height: 40,
                                    borderRadius: 5,
                                }}
                                renderInput={(props) => <input {...props} />}
                            />

                            <Counter/>
                        </div>

                        <div className={`flex flex-col`}>
                            <p className={`font-bold border-bottom font-[12px] ${Auth.senAgain}`}>
                                Send Code Again
                            </p>
                        </div>

                        <div className={`mt-[5px] relative ${Auth.editMail}`}>
                            <p>
                                One-time password sent to “<span> pars.amin.fashion@gmail.com </span>“
                            </p>
                            <Link href={"/auth"}>
                                <Image src={EditMail} alt={"exchanger-auth"} className={"absolute top-[25px] right-[1px] lg:top-[3px]  lg:right-[-20px]"}/>
                            </Link>
                        </div>


                        <button className={"exchange-button flex w-full mb-[20px] mt-[52px]"}>
                            Verify
                        </button>


                        <div className={'flex w-full relative items-center justify-center'}>

                            <div className={Auth.otherLoginLeftLine}/>

                            <p className={"text-[12px]"}>
                                Or continue with
                            </p>

                            <div className={Auth.otherLoginRightLine}/>
                        </div>
                        <div className={"flex w-full justify-center items-center mt-[15px]"}>
                            <Image src={OtherLogin} alt={"login-exchanger"}/>
                        </div>
                    </div>


                </div>
            </div>
        </>
    )
}


export default Otp;