import Head from "next/head";
import Style from "@/styles/components/MainBlock.module.scss";
import Image from "next/image";
import IndexPic from "@/assets/images/IndexPic.png";
import Auth from "@/styles/components/Auth.module.scss";
import Link from "next/link";
import Mail from "@/assets/svg/social/sms.svg";
import Lock from "@/assets/svg/lock.svg";
import OtherLogin from "@/assets/images/otherLogin.png";
import useTitle from "@/CustomHook/useTitle";
import {useState} from "react";
import ArrowLeft from "@/assets/svg/arrow-left.svg";


const Register = () => {



    const [value, setValue] = useState({email: "" , password:"" , confirmPass:""});

    const ManageChange = (e) => {
        setValue({...value, [e.target.name]: e.target.value});
    }

    useTitle("Register")

    return(
        <>
            <Head>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className={"p-6 gap-10 text-white lg:px-8"}>
                <div className={`flex items-center ${Style.mainBlock}`}>
                    <Image className={Style.indexPic} src={IndexPic} alt={"exchanger-web"}/>
                    <h1 className={`text-center ${Style.indexTitle}`}>
            <span className={`${Style.boldTitle} font-bold`}>
              <span className={Style.greenTitle}>A</span>RZICLUB
            </span>
                        <span className={Style.lightTitle}>
               EXCHANGER
            </span>
                    </h1>

                    <div className={`relative w-1/2 flex flex-col items-start ${Auth.loginBox}`}>

                        <div className={"flex w-full items-center justify-between"}>

                             <Link href={"/auth"} className={`flex relative items-center justify-center ${Auth.backBtn}`}>
                                 <Image src={ArrowLeft} alt={"back"} className={"absolute left-[8px]"}/>

                                 <p className={"font-bold text-center ml-[8px]"}>
                                   Back
                                 </p>
                             </Link>

                            <div className={"flex items-center"}>
                                <p className={"lg:text-[18px] text-[12px] font-bold"}>
                                    SING IN
                                </p>
                                <div className={`mx-[10px] ${Auth.titleDivider}`}/>
                                <p className={"lg:text-[18px] text-[12px] font-bold"}>
                                    SING UP
                                </p>
                            </div>
                        </div>

                        <p className={"text-[13px] mb-[29px] mt-[10px]"}>
                            To use ARZICLUB services , log in to your account . <Link href={"/auth"}
                                                                                      className={`font-bold ${Auth.registerLink}`}>Login</Link> if
                            you don't have an account .
                        </p>

                        <div className={"flex-col w-full relative items-center justify-center"}>
                            <h5 className={'mb-[5px]'}>
                                {"Email *"}
                            </h5>

                            <Image src={Mail} alt={"user-comment"}
                                   className={"absolute top-[39px] opacity-[20%] left-[5px]"}/>
                            <input value={value.email} name={"email"} type={"email"} placeholder={"mail@website.com"}
                                   onChange={ManageChange} className={`${Auth.NameInput}`}/>
                        </div>

                        <div className={"grid gap-[20px] w-full grid-cols-1 lg:grid-cols-2 mt-[10px]"}>
                            <div className={"flex-col w-full relative items-center justify-center"}>
                                <h5 className={'mb-[5px]'}>
                                    {"Password *"}
                                </h5>

                                <Image src={Lock} alt={"user-comment"}
                                       className={"absolute top-[40px] left-[8px]"}/>
                                <input value={value.password} name={"password"} type={"password"} placeholder={"min 8 . character"}
                                       onChange={ManageChange} className={`${Auth.NameInput}`}/>
                            </div>

                            <div className={"flex-col w-full relative items-center justify-center"}>
                                <h5 className={'mb-[5px]'}>
                                    {"Confirm Password *"}
                                </h5>

                                <Image src={Lock} alt={"user-comment"}
                                       className={"absolute top-[40px] left-[8px]"}/>
                                <input value={value.confirmPass} name={"confirmPass"} type={"password"} placeholder={"min 8 . character"}
                                       onChange={ManageChange} className={`${Auth.NameInput}`}/>
                            </div>
                        </div>
                        <button className={"exchange-button flex w-full mb-[20px] mt-[36px]"}>
                            Sign in
                        </button>


                        <div className={'flex w-full relative items-center justify-center'}>

                            <div className={Auth.otherLoginLeftLine}/>

                            <p className={"text-[12px]"}>
                                Or continue with
                            </p>

                            <div className={Auth.otherLoginRightLine}/>
                        </div>
                        <div className={"flex w-full justify-center items-center mt-[15px]"}>
                            <Image src={OtherLogin} alt={"login-exchanger"}/>
                        </div>
                    </div>


                </div>
            </div>
        </>
    )
}


export default Register;